const months = [["jan","Styczen"],["feb","Luty"],["mar","Marzec"],["apr","Kwiecien"],["may","Maj"],["jun","Czerwiec"],["jul","Lipiec"],["aug","Sierpien"],["sep","Wrzesien"],["oct","Pazdziernik"],["nov","Listopad"],["dec","Grudzien"]];
const storageKey = "azia-harmonogram-v3";
const backupKey = `${storageKey}-snapshots`;
const sessionKey = "adi-current-user";
const adminCode = "adi01";
const apiUrl = "api.php";
const $ = (selector) => document.querySelector(selector);

const seedData = {
  restaurants: {
    "arkadia": {"name":"Arkadia Azia","manager":"Manager Arkadia Azia","accent":"#a22620","type":"Restauracja","description":"Restauracja w Arkadii","address":"Centrum handlowe Arkadia","phone":"+48 600 000 101","email":"arkadia@azia.pl","progress":0,"sales":{"jan":1107279.22,"feb":1026588.84,"mar":1013258.87,"apr":863271.5,"may":135838.05,"jun":0,"jul":0,"aug":0,"sep":0,"oct":0,"nov":0,"dec":0},"externalSales":{"jan":77333.26,"feb":76228.92,"mar":98238.67,"apr":94775.82,"may":11132.31,"jun":0,"jul":0,"aug":0,"sep":0,"oct":0,"nov":0,"dec":0}},
    "blue-city": {"name":"Blue City Azia","manager":"Manager Blue City Azia","accent":"#1f5d99","type":"Restauracja","description":"Restauracja w Blue City","address":"Centrum handlowe Blue City","phone":"+48 600 000 102","email":"bluecity@azia.pl","progress":0,"sales":{"jan":212151.63,"feb":208600.71,"mar":195997.17,"apr":203834.27,"may":0,"jun":0,"jul":0,"aug":0,"sep":0,"oct":0,"nov":0,"dec":0},"externalSales":{"jan":15495.31,"feb":11044.91,"mar":16954.3,"apr":10227.52,"may":0,"jun":0,"jul":0,"aug":0,"sep":0,"oct":0,"nov":0,"dec":0}},
    "wilanow": {"name":"Wilanow Azia","manager":"Manager Wilanow Azia","accent":"#19784a","type":"Restauracja","description":"Restauracja w Wilanowie","address":"ul. Klimczaka 1","phone":"+48 600 000 103","email":"wilanow@azia.pl","progress":0,"sales":{"jan":272113.6,"feb":290109.45,"mar":417098.25,"apr":340744.35,"may":0,"jun":0,"jul":0,"aug":0,"sep":0,"oct":0,"nov":0,"dec":0},"externalSales":{"jan":70313.69,"feb":61814.99,"mar":58384.58,"apr":45402.9,"may":0,"jun":0,"jul":0,"aug":0,"sep":0,"oct":0,"nov":0,"dec":0}},
    "koneser": {"name":"Koneser Azia","manager":"Manager Koneser Azia","accent":"#7a4a12","type":"Restauracja","description":"Restauracja w Koneserze","address":"Centrum Praskie Koneser","phone":"+48 600 000 104","email":"koneser@azia.pl","progress":0,"sales":{"jan":81000,"feb":83500,"mar":89000,"apr":93000,"may":97200,"jun":0,"jul":0,"aug":0,"sep":0,"oct":0,"nov":0,"dec":0},"externalSales":{"jan":10100,"feb":10600,"mar":11500,"apr":12100,"may":12900,"jun":0,"jul":0,"aug":0,"sep":0,"oct":0,"nov":0,"dec":0}},
    "katowice-loop-bar": {"name":"Katowice Loop Bar","manager":"Piotr Miedzinski","accent":"#7c3aed","type":"Projekt","description":"Katowice Loop Bar","address":"Katowice","phone":"+48 602 134 502","email":"piotr@good4wall.com","progress":30,"sales":{},"externalSales":{}},
    "naori-konstancin": {"name":"Naori Konstancin","manager":"Piotr Miedzinski","accent":"#7c3aed","type":"Projekt","description":"Naori Konstancin","address":"Konstancin","phone":"+48 602 134 502","email":"piotr@good4wall.com","progress":0,"sales":{},"externalSales":{}},
    "punkt-w-blue-citi": {"name":"Punkt w Blue Citi","manager":"Piotr Miedzinski","accent":"#7c3aed","type":"Projekt","description":"Punkt w Blue Citi","address":"Blue City","phone":"+48 602 134 502","email":"piotr@good4wall.com","progress":0,"sales":{},"externalSales":{}},
    "punkt-2-blue-city-kazaczok": {"name":"Punkt 2 Blue City Kazaczok","manager":"Piotr Miedzinski","accent":"#7c3aed","type":"Projekt","description":"Spotkanie o 13 tej w srode","address":"Blue City","phone":"+48 602 134 502","email":"piotr@good4wall.com","progress":0,"sales":{},"externalSales":{}}
  },
  actions: [
    {"id":"a-0","restaurant":"arkadia","area":"Operacje","title":"Standard obslugi sali","description":"","manager":"Manager Arkadia Azia","priority":"Wysoki","dueDate":"2026-05-15","status":"W toku","nextStep":"Dopisac punkty kontroli otwarcia i zamkniecia.","notes":"","updatedAt":"2026-05-10"},
    {"id":"a-1","restaurant":"arkadia","area":"Marketing","title":"Akcja lokalna Arkadia","description":"","manager":"Manager Arkadia Azia","priority":"Sredni","dueDate":"2026-05-22","status":"Do zrobienia","nextStep":"Wybrac oferte i kanaly komunikacji.","notes":"","updatedAt":"2026-05-10"},
    {"id":"a-2","restaurant":"blue-city","area":"Kontrola","title":"Zdjecia pomieszczen","description":"","manager":"Manager Blue City Azia","priority":"Wysoki","dueDate":"2026-05-10","status":"W toku","nextStep":"Ustalic, kto robi zdjecia i gdzie je zapisuje.","notes":"","updatedAt":"2026-05-10"},
    {"id":"a-3","restaurant":"blue-city","area":"Zespol","title":"Grafik odpowiedzialnosci","description":"","manager":"Manager Blue City Azia","priority":"Sredni","dueDate":"2026-05-17","status":"W toku","nextStep":"Uzupelnic nazwiska w planie tygodnia.","notes":"","updatedAt":"2026-05-10"},
    {"id":"a-4","restaurant":"wilanow","area":"Operacje","title":"Audyt jakosci","description":"","manager":"Manager Wilanow Azia","priority":"Sredni","dueDate":"2026-05-18","status":"Do zrobienia","nextStep":"Wyznaczyc dzien audytu.","notes":"","updatedAt":"2026-05-10"},
    {"id":"a-5","restaurant":"koneser","area":"Marketing","title":"Widocznosc lokalu","description":"","manager":"Manager Koneser Azia","priority":"Sredni","dueDate":"2026-05-20","status":"Do zrobienia","nextStep":"Wypisac brakujace materialy.","notes":"","updatedAt":"2026-05-10"},
    {"id":"arkadia-ok-2026-05-30","restaurant":"arkadia","area":"Arkadia Azia","title":"ok","description":"ok","manager":"Koordynator","priority":"Sredni","dueDate":"2026-05-30","status":"Do zrobienia","nextStep":"ok","notes":"","updatedAt":"2026-05-30","attachments":[{"id":"arkadia-ok-photo","name":"Zrzut ekranu 2026-05-29 o 08.22.40.png","type":"image/jpeg","size":18432,"data":"assets/arkadia-ok-thumb.jpg"}]}
  ]
};

let state = loadState();
state.currentUser = loadUser();

const els = {
  loginForm: $("#loginForm"), accessCodeInput: $("#accessCodeInput"), loginError: $("#loginError"), currentAccess: $("#currentAccess"),
  restaurantNav: $("#restaurantNav"), entityDetail: $("#entityDetail"), restaurantOverview: $("#restaurantOverview"), actionsTable: $("#actionsTable"),
  tableTitle: $("#tableTitle"), tableSubtitle: $("#tableSubtitle"), emptyState: $("#emptyState"), statusFilter: $("#statusFilter"), priorityFilter: $("#priorityFilter"), searchInput: $("#searchInput"),
  metricTotal: $("#metricTotal"), metricInProgress: $("#metricInProgress"), metricOverdue: $("#metricOverdue"), metricDone: $("#metricDone"),
  dialog: $("#actionDialog"), form: $("#actionForm"), restaurantInput: $("#restaurantInput"), actionId: $("#actionId"), titleInput: $("#titleInput"), managerInput: $("#managerInput"), dueDateInput: $("#dueDateInput"), priorityInput: $("#priorityInput"), statusInput: $("#statusInput"), broadcastLabel: $("#broadcastLabel"), broadcastAllInput: $("#broadcastAllInput"), nextStepInput: $("#nextStepInput"), descriptionInput: $("#descriptionInput"), notesInput: $("#notesInput"), attachmentsInput: $("#attachmentsInput"), existingAttachments: $("#existingAttachments"),
  restaurantDialog: $("#restaurantDialog"), restaurantForm: $("#restaurantForm"), newRestaurantName: $("#newRestaurantName"), newRestaurantType: $("#newRestaurantType"), newRestaurantManager: $("#newRestaurantManager"), newRestaurantPhone: $("#newRestaurantPhone"), newRestaurantEmail: $("#newRestaurantEmail"), newRestaurantAddress: $("#newRestaurantAddress"), newRestaurantDescription: $("#newRestaurantDescription"), newRestaurantColor: $("#newRestaurantColor"), newProjectProgress: $("#newProjectProgress"),
};

els.loginForm.addEventListener("submit", e => { e.preventDefault(); login(els.accessCodeInput.value); });
$("#logoutButton").addEventListener("click", () => { sessionStorage.removeItem(sessionKey); state.currentUser = null; state.selectedRestaurant = "all"; renderAuth(); });
$("#openActionModal").addEventListener("click", () => safeOpenAction());
$("#openRestaurantModal").addEventListener("click", () => openRestaurant());
$("#printReport").addEventListener("click", () => window.print());
$("#exportCsv").addEventListener("click", exportCsv);
$("#exportBackup").addEventListener("click", exportBackup);
$("#importBackupButton").addEventListener("click", () => $("#importBackupInput").click());
$("#importBackupInput").addEventListener("change", importBackup);
$("#closeDialog").addEventListener("click", () => closeModal(els.dialog));
$("#cancelDialog").addEventListener("click", () => closeModal(els.dialog));
$("#closeRestaurantDialog").addEventListener("click", () => closeModal(els.restaurantDialog));
$("#cancelRestaurantDialog").addEventListener("click", () => closeModal(els.restaurantDialog));
els.restaurantNav.addEventListener("click", e => { const b = e.target.closest("[data-restaurant]"); if (b && canAccess(b.dataset.restaurant)) { state.selectedRestaurant = b.dataset.restaurant; render(); } });
["change","input"].forEach(type => {
  els.statusFilter.addEventListener(type, e => { state.statusFilter = e.target.value; render(); });
  els.priorityFilter.addEventListener(type, e => { state.priorityFilter = e.target.value; render(); });
  els.searchInput.addEventListener(type, e => { state.search = e.target.value.toLowerCase(); render(); });
});
els.restaurantInput.addEventListener("change", () => renderPersonOptions());
els.attachmentsInput.addEventListener("change", renderSelectedAttachments);
els.form.addEventListener("submit", async e => { e.preventDefault(); await saveAction(); });
els.restaurantForm.addEventListener("submit", e => { e.preventDefault(); saveRestaurant(); });
els.entityDetail.addEventListener("click", e => { const b = e.target.closest("button"); if (!b) return; if (b.dataset.entityAction === "add-action") { safeOpenAction(); return; } if (!isAdmin()) return; if (b.dataset.entityAction === "edit") openRestaurant(state.selectedRestaurant); if (b.dataset.entityAction === "delete") deleteRestaurant(state.selectedRestaurant); });
els.entityDetail.addEventListener("submit", e => {
  const sales = e.target.closest(".sales-form"); const progress = e.target.closest("#projectProgressForm");
  if (sales) { e.preventDefault(); updateSales(state.selectedRestaurant, sales.dataset.salesType, sales.querySelector("select").value, parseMoney(sales.querySelector("input").value)); }
  if (progress) { e.preventDefault(); data()[state.selectedRestaurant].progress = clamp(progress.querySelector("input").value); persist(); render(); }
});
els.actionsTable.addEventListener("click", e => { const b = e.target.closest("button"); if (!b) return; const action = state.actions.find(a => a.id === b.dataset.id); if (b.dataset.action === "done" && isAdmin()) updateAction(b.dataset.id, {status:"Zakonczone"}); if (b.dataset.action === "edit" && canEditAction(action)) openAction(action); if (b.dataset.action === "delete" && isAdmin()) { rememberDeleted(b.dataset.id); state.actions = state.actions.filter(a => a.id !== b.dataset.id); persist(); render(); } });

renderAuth();
syncFromServer();

function monthObject(values = {}) { return Object.fromEntries(months.map(([k]) => [k, Number(values[k] || 0)])); }
function loadState() { try { const saved = bestSavedState(); if (saved?.restaurants) { const deletedActionIds = Array.isArray(saved.deletedActionIds) ? saved.deletedActionIds : []; return {selectedRestaurant:"all", statusFilter:"all", priorityFilter:"all", search:"", restaurants: normalize({...clone(seedData.restaurants), ...saved.restaurants}), actions: withoutDeleted(normalizeActions(saved.actions || []), deletedActionIds), deletedActionIds}; } } catch {} return {selectedRestaurant:"all", statusFilter:"all", priorityFilter:"all", search:"", restaurants: normalize(clone(seedData.restaurants)), actions: [], deletedActionIds:[]}; }
function normalize(items) { const out = {}; Object.entries(items).forEach(([k,r]) => out[k] = {...r, sales: monthObject(r.sales), externalSales: monthObject(r.externalSales), employeeCosts: monthObject(r.employeeCosts), b2bCosts: monthObject(r.b2bCosts), progress: clamp(r.progress || 0)}); return out; }
function loadUser() { try { return JSON.parse(sessionStorage.getItem(sessionKey)); } catch { return null; } }
function data() { return state.restaurants; }
function login(code) { code = code.trim().toLowerCase(); let user = code === adminCode ? {role:"admin"} : null; if (!user) { const found = Object.entries(data()).find(([,r]) => accessCode(r) === code); if (found) user = {role:"manager", restaurant:found[0]}; } if (!user) { els.loginError.hidden = false; return; } state.currentUser = user; state.selectedRestaurant = user.role === "admin" ? "all" : user.restaurant; sessionStorage.setItem(sessionKey, JSON.stringify(user)); renderAuth(); }
function renderAuth() { document.body.classList.toggle("authenticated", !!state.currentUser); if (state.currentUser) render(); }
function isAdmin() { return state.currentUser?.role === "admin"; }
function canAccess(k) { return isAdmin() ? k === "all" || !!data()[k] : state.currentUser?.restaurant === k; }
function canEditAction(a) { return !!a && canAccess(a.restaurant); }
function visibleKeys() { return isAdmin() ? Object.keys(data()) : [state.currentUser.restaurant]; }
function restaurantKeys() { return Object.keys(data()).filter(k => data()[k]?.type === "Restauracja"); }
function persist() { persistLocal(); saveServerState(); }
function persistLocal() { const previous = readStored(storageKey); const payload = JSON.stringify({restaurants:state.restaurants, actions:state.actions, deletedActionIds:state.deletedActionIds || [], savedAt:new Date().toISOString()}); saveSnapshot(previous); try { localStorage.setItem(storageKey, payload); } catch { localStorage.removeItem(backupKey); try { localStorage.setItem(storageKey, payload); } catch { alert("Nie udalo sie zapisac danych. Zrob backup JSON i zmniejsz liczbe lub rozmiar zalacznikow."); } } }
function render() { if (state.currentUser?.role === "manager") state.selectedRestaurant = state.currentUser.restaurant; const actions = filteredActions(); renderAccess(); renderNav(); renderOptions(); renderMetrics(actions); renderEntity(); renderOverview(); renderTable(actions); renderTitles(); }
function renderAccess() { els.currentAccess.textContent = isAdmin() ? "Dostep: administrator" : `Dostep: ${data()[state.currentUser.restaurant]?.name}`; ["#exportCsv","#exportBackup","#importBackupButton","#openRestaurantModal"].forEach(s => $(s).hidden = !isAdmin()); $("#openActionModal").hidden = !state.currentUser; }
function renderNav() { const item = type => visibleKeys().filter(k => data()[k].type === type).map(k => `<button class="nav-item ${state.selectedRestaurant===k?"active":""}" data-restaurant="${k}"><strong>${esc(data()[k].name)}</strong><span>${esc(data()[k].description || "")}</span></button>`).join(""); els.restaurantNav.innerHTML = `${isAdmin()?`<button class="nav-item ${state.selectedRestaurant==="all"?"active":""}" data-restaurant="all"><strong>Wszystkie restauracje</strong><span>Lista restauracji i projektow</span></button>`:""}<span class="nav-group-label">Restauracje</span>${item("Restauracja")}<span class="nav-group-label projects">Projekty</span>${item("Projekt") || `<span class="nav-empty">Brak projektow</span>`}`; }
function renderOptions() { els.restaurantInput.innerHTML = visibleKeys().map(k => `<option value="${k}">${esc(data()[k].name)}</option>`).join(""); els.restaurantInput.disabled = !isAdmin(); }
function renderPersonOptions(selected = "") { const manager = data()[els.restaurantInput.value]?.manager || "Manager"; const base = isAdmin() ? ["Boss","Koordynator"] : [manager]; const options = [...new Set([selected, ...base].filter(Boolean))]; if (els.managerInput.tagName === "SELECT") els.managerInput.innerHTML = options.map(v => `<option value="${esc(v)}">${esc(v)}</option>`).join(""); els.managerInput.value = selected || options[0] || ""; }
function renderStatusOptions(selected = "Do zrobienia") { const value = normalizeStatus(selected); const statuses = isAdmin() ? ["Do zrobienia","W toku","Zablokowane","Zakonczone"] : value === "Zakonczone" ? ["Zakonczone"] : ["Do zrobienia","W toku","Zablokowane"]; els.statusInput.innerHTML = statuses.map(v => `<option value="${esc(v)}">${esc(v)}</option>`).join(""); els.statusInput.value = statuses.includes(value) ? value : "W toku"; }
function filteredActions() { return state.actions.filter(a => data()[a.restaurant] && visibleKeys().includes(a.restaurant)).filter(a => isAdmin() && state.selectedRestaurant==="all" ? true : a.restaurant===state.selectedRestaurant).filter(a => state.statusFilter==="all" || a.status===state.statusFilter).filter(a => state.priorityFilter==="all" || a.priority===state.priorityFilter).filter(a => !state.search || [a.title,a.manager,a.nextStep,a.description,data()[a.restaurant].name].join(" ").toLowerCase().includes(state.search)); }
function renderMetrics(actions) { els.metricTotal.textContent = actions.length; els.metricInProgress.textContent = actions.filter(a => a.status==="W toku").length; els.metricOverdue.textContent = actions.filter(overdue).length; els.metricDone.textContent = actions.filter(a => a.status==="Zakonczone").length; }
function renderEntity() { if (state.selectedRestaurant==="all") { els.entityDetail.innerHTML = `<article class="entity-card"><p class="eyebrow">Wszystkie restauracje i projekty</p><h2>Wybierz pozycje z lewego menu, zeby zobaczyc dane kontaktowe i sprzedaz.</h2></article>`; return; } const r = data()[state.selectedRestaurant]; els.entityDetail.innerHTML = `<article class="entity-card" style="${style(r)}"><div class="entity-main"><div><p class="eyebrow">${r.type}</p><h2>${esc(r.name)}</h2><p>${linkify(r.description)}</p></div><div class="entity-actions"><button class="primary-action" data-entity-action="add-action">Dodaj dzialanie</button>${isAdmin()?`<button class="secondary-action" data-entity-action="edit">Edytuj dane</button><button class="secondary-action danger" data-entity-action="delete">Usun</button>`:""}</div></div><div class="detail-grid"><div><span>Manager</span><strong>${esc(r.manager)}</strong></div><div><span>Telefon</span><strong>${esc(r.phone)}</strong></div><div><span>E-mail</span><strong>${esc(r.email)}</strong></div><div><span>Adres / lokalizacja</span><strong>${esc(r.address)}</strong></div>${isAdmin()?`<div><span>Kod managera</span><strong>${accessCode(r)}</strong></div>`:""}</div><div class="whatsapp-row"><a class="whatsapp-button" href="https://wa.me/${wa(r.phone)}" target="_blank">WhatsApp do managera</a><a class="whatsapp-button" href="https://wa.me/48602134502" target="_blank">WhatsApp koordynator</a><a class="whatsapp-button" href="https://wa.me/48605421460" target="_blank">WhatsApp BOSS</a></div>${r.type==="Projekt"?progressPanel(r):financialPanels(r)}</article>`; }
function financialPanels(r) { return salesPanel(r,"sales","Sprzedaz miesieczna","Zapisz sprzedaz") + salesPanel(r,"externalSales","Sprzedaz na zewnatrz","Zapisz sprzedaz") + salesPanel(r,"employeeCosts","Koszty pracownikow","Zapisz koszty") + salesPanel(r,"b2bCosts","Koszty B2B","Zapisz koszty"); }
function salesPanel(r,type,title,buttonLabel) { if (!r[type]) r[type] = monthObject(); const trend = salesTrend(r,type); const next = months.find(([k]) => !r[type][k])?.[0] || "dec"; const scale = chartMax(Object.values(r[type])); return `<div class="sales-panel"><div class="sales-head"><div><h3>${title}</h3><p>Ostatni wpis: ${money(trend.current)} · zmiana m/m: <strong class="${trend.change>=0?"positive":"negative"}">${percent(trend.change)}</strong></p></div><form class="sales-form" data-sales-type="${type}"><select>${months.map(([k,l])=>`<option value="${k}" ${k===next?"selected":""}>${l}</option>`).join("")}</select><input type="text" inputmode="decimal" /><button class="primary-action">${buttonLabel}</button></form></div><div class="sales-chart"><div class="bars">${months.map(([k,l])=>bar(l,r[type][k],scale)).join("")}</div></div><div class="sales-total">Suma wszystkich miesiecy: <strong>${money(total(r,type))}</strong></div></div>`; }
function bar(label,value,max) { const h = value ? Math.max(3, Math.min(100, value / max * 100)) : 0; return `<div class="bar-item"><div class="bar-track"><span style="height:${h}%"></span></div><strong>${label.slice(0,3)}</strong><small>${money(value)}</small></div>`; }
function progressPanel(r) { return `<div class="project-progress-panel"><div class="project-progress-head"><div><h3>Status projektu</h3><p>Zaawansowanie wykonawcze projektu.</p></div><strong class="progress-value">${r.progress}%</strong></div><div class="progress-line"><span style="width:${r.progress}%"></span></div><div class="progress-scale"><span>0%</span><span>25%</span><span>50%</span><span>75%</span><span>100%</span></div><form id="projectProgressForm" class="project-progress-form"><input type="number" min="0" max="100" value="${r.progress}" /><button class="secondary-action">Zapisz status</button></form></div>`; }
function renderOverview() { if (!isAdmin() || state.selectedRestaurant!=="all") { els.restaurantOverview.innerHTML = ""; return; } els.restaurantOverview.innerHTML = `<div class="overview-section"><h2>Restauracje</h2><div class="overview-grid">${cards("Restauracja")}</div></div><div class="overview-section projects"><h2>Projekty</h2><div class="overview-grid">${cards("Projekt")}</div></div>`; }
function cards(type) { return Object.entries(data()).filter(([,r])=>r.type===type).map(([k,r])=>`<article class="restaurant-card" style="${style(r)}"><header><div><h3>${esc(r.name)}</h3><p>${linkify(r.description)}</p></div><span class="card-count">${state.actions.filter(a=>a.restaurant===k).length}</span></header><div class="mini-stats"><span><strong>${state.actions.filter(a=>a.restaurant===k&&a.status!=="Zakonczone").length}</strong> aktywne</span><span><strong>${state.actions.filter(a=>a.restaurant===k&&overdue(a)).length}</strong> po terminie</span>${type==="Projekt"?`<span><strong>${r.progress}%</strong> status</span>`:`<span><strong>${money(salesTrend(r,"sales").current)}</strong> sprzedaz lokalu</span><span><strong>${money(salesTrend(r,"externalSales").current)}</strong> na zewnatrz</span>`}</div></article>`).join(""); }
function renderTable(actions) { els.actionsTable.innerHTML = actions.map(a=>`<tr class="action-row" style="${style(data()[a.restaurant])}"><td><span class="restaurant-pill">${esc(data()[a.restaurant].name)}</span></td><td><strong>${esc(a.title)}</strong><small>${linkify(a.description||"Bez dodatkowego opisu")}</small>${attachmentList(a)}<div class="inline-actions"><button data-action="edit" data-id="${a.id}">Edytuj wpis</button></div></td><td>${esc(a.manager)}</td><td><span class="priority ${a.priority==="Wysoki"?"high":a.priority==="Sredni"?"medium":"low"}">${a.priority}</span></td><td class="${overdue(a)?"overdue":""}">${date(a.dueDate)}</td><td><span class="status">${a.status}</span></td><td><strong>${linkify(a.nextStep)}</strong><small>Aktualizacja: ${date(a.updatedAt)}</small></td><td><div class="row-actions">${isAdmin()?`<button data-action="done" data-id="${a.id}">Zakoncz</button><button data-action="delete" data-id="${a.id}">Usun</button>`:""}</div></td></tr>`).join(""); els.emptyState.hidden = actions.length>0; }
function renderTitles(){ const r=data()[state.selectedRestaurant]; els.tableTitle.textContent=state.selectedRestaurant==="all"?"Wszystkie dzialania":r.name; els.tableSubtitle.textContent=state.selectedRestaurant==="all"?"Pelna lista projektow ze wszystkich lokalizacji.":"Dzialania, terminy i odpowiedzialnosc dla wybranej restauracji."; }
function safeOpenAction(a={}){ try { openAction(a); } catch (error) { console.error(error); alert("Nie udalo sie otworzyc formularza. Odswiez strone i sproboj ponownie."); } }
function openAction(a={}){ if(!state.currentUser)return; els.form.reset(); renderOptions(); const keys = visibleKeys(); const onlyKey = isAdmin() ? keys[0] : state.currentUser.restaurant; if (!onlyKey) return; const selectedKey = a.restaurant || (state.selectedRestaurant === "all" ? onlyKey : state.selectedRestaurant); els.actionId.value=a.id||""; els.restaurantInput.value=canAccess(selectedKey) ? selectedKey : onlyKey; renderPersonOptions(a.manager || (isAdmin() ? "Boss" : data()[els.restaurantInput.value]?.manager || "")); els.titleInput.value=a.title||""; els.dueDateInput.value=a.dueDate||today(); els.priorityInput.value=normalizePriority(a.priority||"Sredni"); renderStatusOptions(a.status||"Do zrobienia"); els.broadcastAllInput.checked=false; els.broadcastLabel.hidden = !isAdmin() || !!a.id; els.nextStepInput.value=a.nextStep||""; els.descriptionInput.value=a.description||""; els.notesInput.value=a.notes||""; renderExistingAttachments(a); openModal(els.dialog); }
async function saveAction(){ const rest = els.restaurantInput.value; if(!state.currentUser || !canAccess(rest))return; const id=els.actionId.value||`a-${Date.now()}`; const existing = state.actions.find(x=>x.id===id); if (existing && !canEditAction(existing)) return; const addedAttachments = await readAttachments(els.attachmentsInput?.files); const targets = isAdmin() && !existing && els.broadcastAllInput.checked ? restaurantKeys() : [rest]; targets.forEach((target, index) => { const actionId = existing ? id : targets.length > 1 ? `${id}-${target}` : id; const current = existing && index === 0 ? existing : null; const chosenStatus = !isAdmin() && els.statusInput.value === "Zakonczone" ? (current?.status || "W toku") : els.statusInput.value; const a={id:actionId,restaurant:target,title:els.titleInput.value,description:els.descriptionInput.value,manager:els.managerInput.value,dueDate:els.dueDateInput.value||today(),priority:els.priorityInput.value,status:chosenStatus,nextStep:els.nextStepInput.value,notes:els.notesInput.value,attachments:[...(current?.attachments||[]),...clone(addedAttachments)],updatedAt:today()}; const i=state.actions.findIndex(x=>x.id===actionId); i>=0?state.actions[i]=a:state.actions.unshift(a); }); persist(); closeModal(els.dialog); render(); }
function openRestaurant(key){ if(!isAdmin())return; const r=data()[key]||{}; els.restaurantForm.dataset.editing=key||""; els.restaurantForm.reset(); els.newRestaurantName.value=r.name||""; els.newRestaurantType.value=r.type||"Restauracja"; els.newRestaurantManager.value=r.manager||""; els.newRestaurantPhone.value=r.phone||""; els.newRestaurantEmail.value=r.email||""; els.newRestaurantAddress.value=r.address||""; els.newRestaurantDescription.value=r.description||""; els.newRestaurantColor.value=r.accent||"#a22620"; els.newProjectProgress.value=r.progress||""; openModal(els.restaurantDialog); }
function saveRestaurant(){ if(!isAdmin())return; const key=els.restaurantForm.dataset.editing||slug(els.newRestaurantName.value); const previous = data()[key] || {}; data()[key]={name:els.newRestaurantName.value,manager:els.newRestaurantManager.value,accent:els.newRestaurantColor.value,type:els.newRestaurantType.value,description:els.newRestaurantDescription.value,address:els.newRestaurantAddress.value,phone:els.newRestaurantPhone.value,email:els.newRestaurantEmail.value,progress:clamp(els.newProjectProgress.value),sales:monthObject(previous.sales),externalSales:monthObject(previous.externalSales),employeeCosts:monthObject(previous.employeeCosts),b2bCosts:monthObject(previous.b2bCosts)}; state.selectedRestaurant=key; persist(); closeModal(els.restaurantDialog); render(); }
function deleteRestaurant(k){ if(isAdmin()&&confirm("Usunac?")){ state.actions.filter(a=>a.restaurant===k).forEach(a=>rememberDeleted(a.id)); delete data()[k]; state.actions=state.actions.filter(a=>a.restaurant!==k); state.selectedRestaurant="all"; persist(); render(); } }
function updateSales(k,type,m,v){ if(canAccess(k)){ if (!data()[k][type]) data()[k][type] = monthObject(); data()[k][type][m]=v; persist(); render(); } }
function updateAction(id,patch){ const a=state.actions.find(x=>x.id===id); if(a&&canAccess(a.restaurant)&&isAdmin()){ Object.assign(a,patch,{updatedAt:new Date().toISOString().slice(0,10)}); persist(); render(); } }
function exportCsv(){ download("adi-harmonogram.csv", filteredActions().map(a=>[data()[a.restaurant].name,a.title,a.manager,a.status].join(";")).join("\n"), "text/csv"); }
function exportBackup(){ download(`adi-backup-${new Date().toISOString().slice(0,10)}.json`, JSON.stringify({restaurants:data(),actions:state.actions,deletedActionIds:state.deletedActionIds || []},null,2), "application/json"); }
async function importBackup(e){ const f=e.target.files[0]; if(!f)return; const b=JSON.parse(await f.text()); state.restaurants=normalize({...state.restaurants, ...(b.restaurants || {})}); state.deletedActionIds = [...new Set([...(state.deletedActionIds || []), ...(b.deletedActionIds || [])])]; state.actions=withoutDeleted(normalizeActions(mergeActions(state.actions, b.actions || [])), state.deletedActionIds); persist(); render(); }
async function syncFromServer(){ if (location.protocol === "file:") return; try { const response = await fetch(`${apiUrl}?t=${Date.now()}`, {cache:"no-store"}); if (!response.ok) return; const remote = await response.json(); if (!remote?.restaurants) return; const merged = mergeState(remote, {restaurants:state.restaurants, actions:state.actions, deletedActionIds:state.deletedActionIds || []}); state.restaurants = normalize(merged.restaurants); state.actions = withoutDeleted(normalizeActions(merged.actions || []), merged.deletedActionIds || []); state.deletedActionIds = merged.deletedActionIds || []; persistLocal(); if (state.currentUser) render(); if ((remote.actions || []).length !== state.actions.length || Object.keys(remote.restaurants || {}).length !== Object.keys(state.restaurants || {}).length) saveServerState(); } catch (error) { console.warn("Brak polaczenia z zapisem serwerowym", error); } }
async function saveServerState(){ if (location.protocol === "file:") return; try { const response = await fetch(apiUrl, {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({restaurants:state.restaurants, actions:state.actions, deletedActionIds:state.deletedActionIds || []})}); if (!response.ok) throw new Error("server"); const remote = await response.json(); if (remote?.restaurants) { const merged = mergeState(remote, {restaurants:state.restaurants, actions:state.actions, deletedActionIds:state.deletedActionIds || []}); state.restaurants = normalize(merged.restaurants); state.actions = withoutDeleted(normalizeActions(merged.actions || []), merged.deletedActionIds || []); state.deletedActionIds = merged.deletedActionIds || []; persistLocal(); if (state.currentUser) render(); } } catch (error) { console.warn("Nie zapisano na serwerze, zostaje kopia lokalna", error); } }
function mergeState(primary = {}, secondary = {}){ const deletedActionIds = [...new Set([...(primary.deletedActionIds || []), ...(secondary.deletedActionIds || [])])]; return {restaurants:{...seedData.restaurants, ...(secondary.restaurants || {}), ...(primary.restaurants || {})}, actions:withoutDeleted(mergeActions((secondary.actions || []).filter(a => !isStarterAction(a)), (primary.actions || []).filter(a => !isStarterAction(a))), deletedActionIds), deletedActionIds}; }
function download(n,c,t){ const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([c],{type:t})); a.download=n; a.click(); URL.revokeObjectURL(a.href); }
function openModal(el){ el.hidden = false; document.body.classList.add("modal-open"); }
function closeModal(el){ el.hidden = true; document.body.classList.remove("modal-open"); }
async function readAttachments(fileList){ const files = Array.from(fileList || []), out = [], skipped = []; for (const file of files) { const image = String(file.type || "").startsWith("image/"); if (image) { out.push(await imageAttachment(file)); continue; } if (file.size > 2000000) { skipped.push(file.name); continue; } out.push({id:fileId(), name:file.name, type:file.type || "application/octet-stream", size:file.size, data:await fileToDataUrl(file)}); } if (skipped.length) alert(`Nie dodano zbyt duzych plikow: ${skipped.join(", ")}. Dodaj mniejszy plik albo zapisz go jako link w uwagach.`); return out; }
async function imageAttachment(file){ try { const data = await compressImage(file); return {id:fileId(), name:file.name, type:"image/jpeg", size:data.length, data}; } catch { return {id:fileId(), name:file.name, type:file.type || "image/png", size:file.size, data:await fileToDataUrl(file)}; } }
function fileId(){ return `f-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function compressImage(file){ return new Promise((resolve,reject)=>{ const img = new Image(); img.onload = () => { const max = 1200, scale = Math.min(1, max / Math.max(img.width, img.height)); const canvas = document.createElement("canvas"); canvas.width = Math.max(1, Math.round(img.width * scale)); canvas.height = Math.max(1, Math.round(img.height * scale)); canvas.getContext("2d").drawImage(img, 0, 0, canvas.width, canvas.height); URL.revokeObjectURL(img.src); resolve(canvas.toDataURL("image/jpeg", .72)); }; img.onerror = reject; img.src = URL.createObjectURL(file); }); }
function fileToDataUrl(file){ return new Promise((resolve,reject)=>{ const reader = new FileReader(); reader.onload=()=>resolve(reader.result); reader.onerror=reject; reader.readAsDataURL(file); }); }
function attachmentList(a){ const files = Array.isArray(a.attachments) ? a.attachments : []; if (!files.length) return ""; return `<div class="attachment-list">${files.map(attachmentItem).join("")}</div>`; }
function renderExistingAttachments(a={}){ const html = attachmentList(a); els.existingAttachments.innerHTML = html ? `<strong>Dodane zdjecia i pliki</strong>${html}` : ""; }
function renderSelectedAttachments(){ const current = state.actions.find(a => a.id === els.actionId.value); const existing = attachmentList(current || {}); const files = Array.from(els.attachmentsInput.files || []); if (!files.length) { renderExistingAttachments(current || {}); return; } const previews = files.map(file => ({name:file.name, type:file.type, data:String(file.type || "").startsWith("image/") ? URL.createObjectURL(file) : ""})); els.existingAttachments.innerHTML = `${existing ? `<strong>Dodane zdjecia i pliki</strong>${existing}` : ""}<strong>Nowe pliki do dodania</strong><div class="attachment-list">${previews.map(attachmentItem).join("")}</div>`; }
function attachmentItem(f){ const image = String(f.type || "").startsWith("image/"); if (image && f.data) return `<a class="attachment-thumb" href="${esc(f.data)}" download="${esc(f.name)}" target="_blank" title="${esc(f.name)}"><img src="${esc(f.data)}" alt="${esc(f.name)}" /><span>${esc(f.name)}</span></a>`; if (image) return `<span class="attachment-thumb attachment-placeholder" title="${esc(f.name)}"><span class="attachment-icon" aria-hidden="true"></span><span>${esc(f.name)}</span></span>`; return `<a class="attachment-file" href="${esc(f.data)}" download="${esc(f.name)}" target="_blank" title="${esc(f.name)}"><span>${esc(f.name)}</span></a>`; }
function total(r,t){ return Object.values(r[t] || {}).reduce((a,b)=>a+Number(b||0),0); }
function salesTrend(r,t){ const v=months.map(([k])=>Number((r[t] || {})[k]||0)).filter(Boolean); const current=v.at(-1)||0, previous=v.at(-2)||0; return {current,change:previous?(current-previous)/previous:0}; }
function chartMax(v){ const m=Math.max(...v.map(Number),1); if(m<=1000000)return Math.ceil(m/100000)*100000; if(m<=5000000)return Math.ceil(m/500000)*500000; return Math.ceil(m/1000000)*1000000; }
function parseMoney(v){ const raw=String(v).trim(), n=Number(raw.replace(/\s/g,"").replace(",", ".")); return Number.isFinite(n)?(((raw.includes(",")||raw.includes("."))&&n<1000)?n*1000000:n):0; }
function money(v){ return `${new Intl.NumberFormat("pl-PL",{maximumFractionDigits:0}).format(Math.trunc(Number(v)||0))} zl`; }
function percent(v){ return new Intl.NumberFormat("pl-PL",{style:"percent",maximumFractionDigits:1,signDisplay:"exceptZero"}).format(v||0); }
function date(v){ return v?new Intl.DateTimeFormat("pl-PL").format(new Date(v)):"Brak terminu"; }
function today(){ return new Date().toISOString().slice(0,10); }
function overdue(a){ const d=new Date(); d.setHours(0,0,0,0); return a.dueDate&&a.status!=="Zakonczone"&&new Date(a.dueDate)<d; }
function style(r){ return `--restaurant-accent:${r.accent};--restaurant-soft:${rgba(r.accent,.08)};--restaurant-line:${rgba(r.accent,.28)}`; }
function wa(phone){ return String(phone || "").replace(/\D/g,""); }
function rgba(h,a){ const c=(h||"#ad2724").replace("#",""),n=parseInt(c,16); return `rgba(${n>>16&255},${n>>8&255},${n&255},${a})`; }
function accessCode(r){ return r.name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ł/g,"l").split(/[^a-z0-9]+/).filter(Boolean).map(w=>w[0]).join("").slice(0,4); }
function slug(v){ return v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ł/g,"l").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""); }
function clamp(v){ return Math.max(0,Math.min(100,Math.round(Number(v)||0))); }
function esc(v){ return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])); }
function linkify(v){ return esc(v).replace(/(https?:\/\/[^\s<]+|www\.[^\s<]+)/gi, url => { const clean = url.replace(/[.,;:!?)]$/, ""); const trail = url.slice(clean.length); const href = clean.startsWith("http") ? clean : `https://${clean}`; return `<a class="text-link" href="${href}" target="_blank" rel="noopener noreferrer">${clean}</a>${trail}`; }); }
function clone(value){ return JSON.parse(JSON.stringify(value)); }
function readStored(key){ try { return JSON.parse(localStorage.getItem(key)); } catch { return null; } }
function bestSavedState(){ const saved = readStored(storageKey); const snapshots = Array.isArray(readStored(backupKey)) ? readStored(backupKey).map(s => s.data).filter(s => s?.restaurants) : []; const deletedActionIds = [...new Set([...(snapshots.flatMap(s => s.deletedActionIds || [])), ...(saved?.deletedActionIds || [])])]; const snapshotActions = snapshots.flatMap(s => s.actions || []).filter(a => !isStarterAction(a)); const recoveredActions = withoutDeleted(mergeActions(snapshotActions, saved?.actions || []), deletedActionIds); if (saved?.restaurants) return {...saved, actions: recoveredActions, deletedActionIds}; const recovered = snapshots[0]; return recovered ? {...recovered, actions: withoutDeleted(mergeActions(snapshotActions), deletedActionIds), deletedActionIds} : null; }
function isStarterAction(a){ return ["a-0","a-1","a-2","a-3","a-4","a-5"].includes(a?.id); }
function saveSnapshot(saved){ if (!saved?.restaurants) return; try { const snapshots = Array.isArray(readStored(backupKey)) ? readStored(backupKey) : []; snapshots.unshift({savedAt:new Date().toISOString(), data:saved}); localStorage.setItem(backupKey, JSON.stringify(snapshots.slice(0,12))); } catch {} }
function rememberDeleted(id){ if (!id) return; state.deletedActionIds = [...new Set([...(state.deletedActionIds || []), id])]; }
function withoutDeleted(actions, ids = state.deletedActionIds || []){ const deleted = new Set(ids); return actions.filter(a => !deleted.has(a.id)); }
function mergeActions(...lists){ const map = new Map(); lists.flat().filter(a => a?.id).forEach(a => map.set(a.id, mergeAction(map.get(a.id), a))); return [...map.values()]; }
function mergeAction(previous = {}, next = {}){ return {...previous, ...next, attachments:mergeAttachments(previous.attachments, next.attachments)}; }
function mergeAttachments(previous = [], next = []){ const map = new Map(); [...previous, ...next].filter(f => f?.id || f?.name).forEach(f => { const key = f.id || f.name; const old = map.get(key) || {}; map.set(key, {...old, ...f, data:f.data || old.data || ""}); }); return [...map.values()]; }
function normalizeActions(actions){ return actions.map(a => ({...a, attachments:Array.isArray(a.attachments)?a.attachments:[], priority: normalizePriority(a.priority), status: normalizeStatus(a.status)})); }
function normalizePriority(v){ return {"Średni":"Sredni","średni":"Sredni","Sredni":"Sredni","Wysoki":"Wysoki","Niski":"Niski"}[v] || "Sredni"; }
function normalizeStatus(v){ return {"Zakończone":"Zakonczone","Zakonczone":"Zakonczone","Do zrobienia":"Do zrobienia","W toku":"W toku","Zablokowane":"Zablokowane"}[v] || "Do zrobienia"; }
